#
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-model-armor-template
  source:
    type: git
    git:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-model-armor-template.git
      dir: /
  version: 0.1.0
spec:
  info:
    title: Vertex AI Model Armor Template
    actuationTool:
      type: Terraform
      versions:
        - ">= 1.3.0"
    descriptions:
      tagline: A Terraform module to create and manage Vertex AI Model Armor templates.
      detailed: |
        This blueprint deploys a Google Cloud Model Armor Template. Model Armor templates define a reusable set of security policies that can be applied to Vertex AI endpoints to protect models from misuse and adversarial attacks. It supports configuring threat detection, input validation, output scrubbing, and logging policies.
    labels:
      - gcp
      - terraform
      - vertex-ai
      - security
      - ai/ml
  content:
    # Starter example of how to use this module
    examples:
      - name: simple_example
        location: examples/simple_example
        title: Simple Model Armor Template
        description: A basic example of a Model Armor template with threat detection.
  interface:
    variables:
      - name: project_id
        description: The GCP project ID where the Model Armor template will be created.
        type: string
        required: true
      - name: location
        description: The GCP location where the Model Armor template will be created.
        type: string
        required: true
      - name: template_id
        description: The unique identifier for the Model Armor template. This value is used for the 'name' argument of the resource.
        type: string
        required: true
      - name: display_name
        description: The user-friendly name for the Model Armor template.
        type: string
        required: true
      - name: description
        description: A detailed description of the Model Armor template's purpose.
        type: string
        default: null
      - name: threat_detection_policy
        description: Configuration for the threat detection policy against adversarial attacks and prompt injection. Set to null to disable.
        type: object
        default: null
      - name: input_validation_safety_attributes
        description: Configuration for the input validation policy, which blocks harmful content. Set to null to disable. Allowed values for each attribute are 'BLOCKING_SCORE_UNSPECIFIED', 'BLOCK_NONE', 'BLOCK_LOW_AND_ABOVE', 'BLOCK_MEDIUM_AND_ABOVE', 'BLOCK_HIGH'.
        type: object
        default: null
      - name: output_scrubbing_pii_detection
        description: Configuration for the output scrubbing policy, which detects and redacts PII. Set to null to disable.
        type: object
        default: null
      - name: logging_config
        description: Configuration for logging detected incidents to a Pub/Sub topic. Set to null to disable.
        type: object
        default: null
    variableGroups:
      - name: General Settings
        description: Basic configuration for the Model Armor template.
        variables:
          - project_id
          - location
          - template_id
          - display_name
          - description
      - name: Security Policies
        description: Configure the security policies for threat detection, input validation, and output scrubbing.
        variables:
          - threat_detection_policy
          - input_validation_safety_attributes
          - output_scrubbing_pii_detection
      - name: Logging
        description: Configure logging for detected security incidents.
        variables:
          - logging_config
    outputs:
      - name: id
        description: The unique ID of the Model Armor template.
      - name: name
        description: The full resource name of the Model Armor template.
      - name: create_time
        description: The creation timestamp of the Model Armor template.
      - name: update_time
        description: The last update timestamp of the Model Armor template.
  requirements:
    roles:
      - level: project
        roles:
          - roles/aiplatform.admin
    services:
      - aiplatform.googleapis.com
      - pubsub.googleapis.com # Required if logging is enabled
    permissions:
      - aiplatform.modelArmorTemplates.create
      - aiplatform.modelArmorTemplates.get
      - aiplatform.modelArmorTemplates.update
      - aiplatform.modelArmorTemplates.delete
