apiVersion: blueprints.cloud.google.com/v1alpha1
kind: TerraformBlueprint
metadata:
  name: terraform-google-model-armor-policy
  source:
    type: git
    # Using a placeholder as the actual repo URL is not provided.
    location: https://github.com/GoogleCloudPlatform/terraform-google-model-armor-policy.git
  version: 1.0.0 # Placeholder version
  actuationTool:
    type: Terraform
    versions:
    - ">= 1.0"
  title: Cloud Armor Security Policy
  descriptions:
    tagline: A Terraform module to create and configure a Google Cloud Armor security policy.
    detailed: This module creates a Google Cloud Armor security policy to protect backend services and endpoints. It supports rules based on IP ranges and custom CEL expressions, including rate limiting options.
  labels:
    product: "Cloud Armor"
    use-case: "security"
spec:
  terraform:
    versionConstraints: ">= 1.0"
    providerRequirements:
      - name: google-beta
        source: hashicorp/google-beta
        version: ">= 4.23.0"
  interfaces:
    variables:
      - name: project_id
        description: The ID of the Google Cloud project where the Model Armor security policy will be created. If not provided, the provider project is used.
        varType: string
        defaultValue: null
        required: false
      - name: name
        description: The name of the Model Armor security policy.
        varType: string
        defaultValue: "model-armor-policy-example"
        required: false
      - name: rules
        description: |
          A list of security rules to apply. Each rule must have a unique priority.
          A rule must specify exactly one of `match_ip_ranges` or `match_expression`.
          - `match_ip_ranges`: A list of CIDR ranges to match. Use `["*"]` to match all traffic.
          - `match_expression`: A CEL expression for advanced matching. For predefined rules like WAF, use an expression like `evaluatePreconfiguredExpr('owasp-crs-v33-stable')`.
          - `rate_limit_options`: Required for `rate_based_ban` or `throttle` actions.
        varType: List<Object>
        defaultValue: []
        required: false
      - name: description
        description: An optional description for the Model Armor security policy.
        varType: string
        defaultValue: null
        required: false
      - name: default_rule_action
        description: The action for the default rule, which applies to all traffic not matched by other rules. This rule has the lowest priority. Must be 'allow' or 'deny'.
        varType: string
        defaultValue: "allow"
        required: false
    variableGroups:
      - name: "Basic Configuration"
        description: "General settings for the security policy."
        variables:
          - project_id
          - name
          - description
      - name: "Policy Rules"
        description: "Define the rules and default behavior for the policy."
        variables:
          - rules
          - default_rule_action
    outputs:
      - name: id
        description: The fully qualified ID of the security policy.
      - name: name
        description: The name of the security policy.
      - name: self_link
        description: The URI of the created security policy.
  requirements:
    roles:
      - level: project
        roles:
          - roles/compute.securityAdmin
    services:
      - compute.googleapis.com
