#
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-model-armor-template
  source:
    repo: https://github.com/GoogleCloudPlatform/terraform-google-model-armor-template # Placeholder URL
    sourceType: git
spec:
  info:
    title: Vertex AI Model Armor Template
    version: 1.0.0
    actuationTool:
      type: Terraform
      versions: [ ">= 1.3" ]
    description:
      tagline: A Terraform module to create and manage Google Cloud Vertex AI Model Armor templates.
      detailed: This module creates a Google Cloud Model Armor template to protect Vertex AI model endpoints from adversarial attacks. It allows for flexible configuration of policy rules, logging, and notifications.
    examples:
      - name: simple_example
        location: examples/simple_example
        title: Simple Model Armor Template
    labels:
      - gcp
      - vertex-ai
      - security
      - model-armor
    documentations:
      - title: GCP Model Armor documentation
        url: https://cloud.google.com/vertex-ai/docs/model-monitoring/model-armor
      - title: Terraform Provider Documentation
        url: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/model_armor_template
  requirements:
    roles:
      - level: project
        roles:
          - roles/aiplatform.admin
          - roles/bigquery.dataEditor # Required if logging is enabled
          - roles/pubsub.publisher # Required if notifications are enabled
    services:
      - aiplatform.googleapis.com
      - bigquery.googleapis.com
      - pubsub.googleapis.com
  customization:
    variables:
      - name: template_id
        description: The ID of the Model Armor template.
        type: String
        required: true
      - name: display_name
        description: The display name of the Model Armor template.
        type: String
        required: true
      - name: location
        description: The GCP region where the Model Armor template will be created.
        type: String
        required: true
      - name: project_id
        description: The GCP project ID where the Model Armor template will be created. If not provided, the provider project is used.
        type: String
        required: false
      - name: description
        description: An optional description for the Model Armor template.
        type: String
        required: false
      - name: labels
        description: A map of key/value labels to apply to the Model Armor template.
        type: Map<String>
        required: false
        default: {}
      - name: default_rule_action
        description: "The default action to take when no rules match a request. Valid values are 'ALLOW' or 'BLOCK'."
        type: String
        required: false
        default: "ALLOW"
      - name: policy_rules
        description: A list of policy rules to apply. Each rule defines a set of conditions (attack signatures) and an action to take upon match.
        type: List<Object>
        required: false
        default: []
      - name: enable_logging
        description: Whether to enable logging of detected threats. If true, `log_destination_bigquery` must be provided.
        type: Bool
        required: false
        default: false
      - name: log_destination_bigquery
        description: "The BigQuery dataset to write threat logs to. Required if `enable_logging` is true. Format: `projects/{project}/datasets/{dataset}`."
        type: String
        required: false
      - name: notification_pubsub_topic
        description: "The full resource name of the Pub/Sub topic to send security event notifications to. Format: `projects/{project}/topics/{topic}`."
        type: String
        required: false
    variableGroups:
      - name: General Settings
        description: Basic configuration for the Model Armor template.
        variables:
          - display_name
          - template_id
          - project_id
          - location
          - description
          - labels
      - name: Policy Configuration
        description: Define the security rules for the template.
        variables:
          - default_rule_action
          - policy_rules
      - name: Monitoring and Notifications
        description: Configure logging and notifications for security events.
        variables:
          - enable_logging
          - log_destination_bigquery
          - notification_pubsub_topic
    outputs:
      - name: id
        description: The full resource ID of the created Model Armor template.
      - name: name
        description: The full resource name of the Model Armor template.
      - name: create_time
        description: The creation timestamp of the Model Armor template.
      - name: update_time
        description: The last update timestamp of the Model Armor template.
